# Generated by Django 5.0.4 on 2024-04-30 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_author_user_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='user_rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
